apiVersion: v1
kind: Service
metadata:
  name: es-nlb
  namespace: dynamic-ads
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    external-dns.alpha.kubernetes.io/hostname: es-nlb.dynamic-ads.smartnews.net
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: elasticsearch-master
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch-master